version: '{branch}-{build}'

build:
  verbosity: minimal

environment:
  matrix:
  - BUILD: 'Release'
    CONFIG: installer
    SHADOW_BUILD_DIR: C:\projects\qgroundcontrol\build_windows_install

install:
  - git submodule update --init --recursive
  - call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - set PATH=C:\Qt\Tools\QtCreator\bin;C:\Qt\5.8\msvc2015\bin;%PATH%
  - mkdir %LOCALAPPDATA%\QtProject && copy test\qtlogging.ini %LOCALAPPDATA%\QtProject\
  - ps: |
      Write-Host "Installing GStreamer..." -ForegroundColor Cyan
      $msiPath = "$($env:USERPROFILE)\gstreamer-1.0-x86-1.5.2.msi"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile('https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/gstreamer-1.0-x86-1.5.2.msi', $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green
  - ps: |
      Write-Host "Installing GStreamer dev..." -ForegroundColor Cyan
      $msiPath = "$($env:USERPROFILE)\gstreamer-1.0-devel-x86-1.5.2.msi"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile('https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/gstreamer-1.0-devel-x86-1.5.2.msi', $msiPath)
      Write-Host "Installing..."
      cmd /c start /wait msiexec /package $msiPath /passive ADDLOCAL=ALL
      Write-Host "Installed" -ForegroundColor Green

build_script:
  - mkdir %SHADOW_BUILD_DIR% && cd %SHADOW_BUILD_DIR% && C:\Qt\5.8\msvc2015\bin\qmake -r CONFIG-=debug_and_release CONFIG+=%CONFIG% CONFIG+=WarningsAsErrorsOn %APPVEYOR_BUILD_FOLDER%\qgroundcontrol.pro
  - cd %SHADOW_BUILD_DIR% && jom
  - if "%CONFIG%" EQU "installer" ( copy %SHADOW_BUILD_DIR%\release\SenteraGroundControl-installer.exe %APPVEYOR_BUILD_FOLDER%\SenteraGroundControl-installer.exe )
  - if "%CONFIG%" EQU "installer" ( copy %SHADOW_BUILD_DIR%\release\SenteraGroundControl.pdb %APPVEYOR_BUILD_FOLDER%\SenteraGroundControl.pdb )
  - if "%CONFIG%" EQU "installer" ( copy %SHADOW_BUILD_DIR%\release\SenteraGroundControl.exe %APPVEYOR_BUILD_FOLDER%\SenteraGroundControl.exe )

test_script:
  - if "%CONFIG%" EQU "debug" ( %SHADOW_BUILD_DIR%\debug\qgroundcontrol --unittest )

artifacts:
  - path: SenteraGroundControl-installer.exe
    name: qgcinstaller
  - path: SenteraGroundControl.pdb
    name: qgcpdb
  - path: SenteraGroundControl.exe
    name: qgcexe
  - path: symbols\**\*.*_
    name: symbols

deploy:
  - provider: GitHub
    auth_token:
      secure: BUS9T0wLsoa/LEhGg7mFETVLo1MfOuwsggKzRm8n4EGdqpqJt9ksFTDqebJJ3yNC
    artifact: qgcinstaller
    draft: false
    prerelease: true
    on:
      CONFIG: installer
      appveyor_repo_tag: false

